trigger:
- main
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service deployment'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: '0aef1d9c-76d5-49fa-ba41-aa793d998aca'
    appName: 'p-m-t-ks5rqp3cc57aa'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
